/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumUserCuisinePreferences } from "./EnumUserCuisinePreferences";
import {
  IsEnum,
  IsOptional,
  IsString,
  MaxLength,
  IsInt,
  Min,
  Max,
} from "class-validator";
import { EnumUserDietaryRestrictions } from "./EnumUserDietaryRestrictions";
import { EnumUserPriceRange } from "./EnumUserPriceRange";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    enum: EnumUserCuisinePreferences,
    isArray: true,
  })
  @IsEnum(EnumUserCuisinePreferences, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumUserCuisinePreferences], {
    nullable: true,
  })
  cuisinePreferences?: Array<"Option1">;

  @ApiProperty({
    required: false,
    enum: EnumUserDietaryRestrictions,
    isArray: true,
  })
  @IsEnum(EnumUserDietaryRestrictions, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumUserDietaryRestrictions], {
    nullable: true,
  })
  dietaryRestrictions?: Array<"Option1">;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  locationRadius?: number | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    enum: EnumUserPriceRange,
  })
  @IsEnum(EnumUserPriceRange)
  @IsOptional()
  @Field(() => EnumUserPriceRange, {
    nullable: true,
  })
  priceRange?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
